table ml_lc_09_global_importance
	lineageTag: d052c9a8-f890-4dfa-91e6-87b9a3196426

	column rank
		dataType: int64
		formatString: 0
		lineageTag: 69d671a7-d4c7-41cf-8880-3095285719fe
		summarizeBy: none
		sourceColumn: rank

		annotation SummarizationSetBy = Automatic

	column original_feature
		dataType: string
		lineageTag: 1c235fc1-4a8b-432a-b632-39f6599ede62
		summarizeBy: none
		sourceColumn: original_feature

		annotation SummarizationSetBy = Automatic

	column feature
		dataType: string
		lineageTag: 45c5bdb7-8042-4d8f-be35-e5c13acef84c
		summarizeBy: none
		sourceColumn: feature

		annotation SummarizationSetBy = Automatic

	column mean_abs_shap
		dataType: double
		lineageTag: 09018541-5ae8-42f5-98fd-30bd0a3e1c0e
		summarizeBy: sum
		sourceColumn: mean_abs_shap

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column xgboost_gain
		dataType: double
		lineageTag: e9ba697a-ec4c-43f8-9db7-fa9608192f64
		summarizeBy: sum
		sourceColumn: xgboost_gain

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column transformed_feature_count
		dataType: int64
		formatString: 0
		lineageTag: 4fd5cf65-6987-4db9-aea1-5fd52293e774
		summarizeBy: sum
		sourceColumn: transformed_feature_count

		annotation SummarizationSetBy = Automatic

	column direction_summary
		dataType: string
		lineageTag: 869c8db9-7441-439d-a68c-d262d9a66a0f
		summarizeBy: none
		sourceColumn: direction_summary

		annotation SummarizationSetBy = Automatic

	column 'Feature Color' =
			
			SWITCH(
			    TRUE(),
			    'ml_lc_09_global_importance'[rank] = 1, "#1455A3",
			    'ml_lc_09_global_importance'[rank] <= 3, "#5592D6",
			    "#D5DAE3"
			)
		lineageTag: 0bdf86e9-bc89-493e-83aa-625226df77b2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Feature EN' =
			
			SWITCH(
			    'ml_lc_09_global_importance'[original_feature],
			    "term_months", "Term (Months)",
			    "loan_to_income_ratio", "Loan / Income",
			    "fico_range_low", "FICO Score",
			    "dti", "DTI Ratio",
			    "issue_year", "Issue Year",
			    "acc_open_past_24mths", "Acc Open (24M)",
			    "home_ownership", "Home Ownership",
			    "mths_since_recent_inq", "Months Since Inquiry",
			    "tot_hi_cred_lim", "Total Credit Limit",
			    "mort_acc", "Mortgage Acc",
			    'ml_lc_09_global_importance'[original_feature]
			)
		lineageTag: 2c18c480-0f3c-4ee6-bb15-fc79de771398
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition ml_lc_09_global_importance = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("D:\Huy\HCMUTE\Nam3\D1\TTDL\DACK\credit-risk-analytics-and-prediction\data\processed\modeling\ml_lc_09_global_importance.csv"), [Delimiter = ",", Columns = 7, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"rank", Int64.Type}, {"original_feature", type text}, {"feature", type text}, {"mean_abs_shap", type number}, {"xgboost_gain", type number}, {"transformed_feature_count", Int64.Type}, {"direction_summary", type text}})
				in
				  #"Changed column type"

