table ml_lc_09_global_importance
	lineageTag: 9f966437-71a2-471e-900c-c8cb5159a625

	column rank
		dataType: int64
		formatString: 0
		lineageTag: 42eef873-e588-4877-b3d5-e83eb81b57cb
		summarizeBy: sum
		sourceColumn: rank

		annotation SummarizationSetBy = Automatic

	column original_feature
		dataType: string
		lineageTag: 1d1d84c0-f38f-4626-9405-f1ad2af33fff
		summarizeBy: none
		sourceColumn: original_feature

		annotation SummarizationSetBy = Automatic

	column feature
		dataType: string
		lineageTag: e898113e-de91-491b-92e0-473c66d4976a
		summarizeBy: none
		sourceColumn: feature

		annotation SummarizationSetBy = Automatic

	column mean_abs_shap
		dataType: double
		lineageTag: c7070c59-a973-46a6-b6f9-5aa9bdf7f869
		summarizeBy: sum
		sourceColumn: mean_abs_shap

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column xgboost_gain
		dataType: double
		lineageTag: af5cfa3f-98e2-47ed-8d6f-cb14bce506a7
		summarizeBy: sum
		sourceColumn: xgboost_gain

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column transformed_feature_count
		dataType: int64
		formatString: 0
		lineageTag: 3b358e1a-00fe-40e8-bc65-42a8bca1e1c2
		summarizeBy: sum
		sourceColumn: transformed_feature_count

		annotation SummarizationSetBy = Automatic

	column direction_summary
		dataType: string
		lineageTag: 3315517f-d556-4302-bbdb-089464b9cf6e
		summarizeBy: none
		sourceColumn: direction_summary

		annotation SummarizationSetBy = Automatic

	column 'Feature Color' =

			SWITCH(
			    TRUE(),
			    ml_lc_09_global_importance[rank] = 1, "#1455A3",
			    ml_lc_09_global_importance[rank] <= 3, "#5592D6",
			    "#D5DAE3"
			)
		lineageTag: 8193d442-57e7-4a57-9de9-559201180c23
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Feature EN' =

			SWITCH(
			    'ml_lc_09_global_importance'[original_feature],
			    "term_months", "Term (Months)",
			    "loan_to_income_ratio", "Loan / Income",
			    "fico_range_low", "FICO Score",
			    "dti", "DTI Ratio",
			    "issue_year", "Issue Year",
			    "acc_open_past_24mths", "Acc Open (24M)",
			    "home_ownership", "Home Ownership",
			    "mths_since_recent_inq", "Months Since Inquiry",
			    "tot_hi_cred_lim", "Total Credit Limit",
			    "mort_acc", "Mortgage Acc",
			    'ml_lc_09_global_importance'[original_feature]
			)
		lineageTag: e1b2840d-e28d-411c-b06a-0ffbcc140300
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition ml_lc_09_global_importance = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\ttdltq\data\processed\modeling\ml_lc_09_global_importance.csv"),[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"rank", Int64.Type}, {"original_feature", type text}, {"feature", type text}, {"mean_abs_shap", type number}, {"xgboost_gain", type number}, {"transformed_feature_count", Int64.Type}, {"direction_summary", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
