table ml_lc_09_local_explanations
	lineageTag: 583927e7-8a3c-41ee-bbde-7a5b575d56eb

	column loan_id
		dataType: int64
		formatString: 0
		lineageTag: 65417643-14bd-4fb3-b9b7-e40b32f9fe87
		summarizeBy: sum
		sourceColumn: loan_id

		annotation SummarizationSetBy = Automatic

	column target
		dataType: int64
		formatString: 0
		lineageTag: 0f440085-8c8e-4499-acf0-8f2157e2434b
		summarizeBy: sum
		sourceColumn: target

		annotation SummarizationSetBy = Automatic

	column predicted_pd
		dataType: double
		lineageTag: dd6e368a-feaf-4b59-bc9b-ed1b5e41ff42
		summarizeBy: sum
		sourceColumn: predicted_pd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column predicted_class
		dataType: int64
		formatString: 0
		lineageTag: 935964e1-7b82-4a84-b234-01388444adee
		summarizeBy: sum
		sourceColumn: predicted_class

		annotation SummarizationSetBy = Automatic

	column risk_example_type
		dataType: string
		lineageTag: 4ec74549-20ac-4d40-88b2-119f3d708ce3
		summarizeBy: none
		sourceColumn: risk_example_type

		annotation SummarizationSetBy = Automatic

	column feature
		dataType: string
		lineageTag: 266e5f87-49f7-4fd1-aafe-65a6bef85b8e
		summarizeBy: none
		sourceColumn: feature

		annotation SummarizationSetBy = Automatic

	column feature_value
		dataType: string
		lineageTag: 9fdc46da-771a-47d4-95e3-99835517b3a9
		summarizeBy: none
		sourceColumn: feature_value

		annotation SummarizationSetBy = Automatic

	column shap_value
		dataType: double
		lineageTag: ff992e94-5a67-41ef-84a7-81b91013f3af
		summarizeBy: sum
		sourceColumn: shap_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column direction
		dataType: string
		lineageTag: 18662eee-c3a6-40d6-9212-a00d4f4c495b
		summarizeBy: none
		sourceColumn: direction

		annotation SummarizationSetBy = Automatic

	column rank
		dataType: int64
		formatString: 0
		lineageTag: 8f17a743-4b4d-42ba-8836-c4504b50e524
		summarizeBy: sum
		sourceColumn: rank

		annotation SummarizationSetBy = Automatic

	partition ml_lc_09_local_explanations = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\ttdltq\data\processed\modeling\ml_lc_09_local_explanations.csv"),[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"loan_id", Int64.Type}, {"target", Int64.Type}, {"predicted_pd", type number}, {"predicted_class", Int64.Type}, {"risk_example_type", type text}, {"feature", type text}, {"feature_value", type text}, {"shap_value", type number}, {"direction", type text}, {"rank", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
